default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: study_mates_development

test:
  <<: *default
  database: study_mates_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>